### PR TITLE
Firebird SQL Support

### PR DESCRIPTION
**Pull request by jjrdk**
I added support for Firebird SQL databases.

There are some tweaks around the tests to have them run against the embedded version of Firebird (in process), but should otherwise follow the standard pattern.

### CODE REVIEW

**Comment by jjrdk** [comment]
Is the project still alive?

**Comment by andreabalducci** [comment]
yes, It's alive. Firebird was dropped in V5, we have discussed on adding back Firebird support after your PR. In V6 we'are splitting the providers & serializers in separate modules so we think that Firebird support should be a "community contrib engine" project, we can't support it as core sql engine. 

We are moving on a new teamcity CI build system with semver to start pushing new stuff (hope to have all up & running this week). We can add a CI build for Firebird on your contrib persistence engine.

**Comment by jjrdk** [comment]
I'll set up a separate NEventStore.Persistence.Firebird project.

Out of interest, why did you drop support for Firebird?

**Comment by Iridio** [comment]
As Andrea told you, we can not support directly all the sql engines, so having the concept of "community contrib engine" would allow everyone to add support to any engine without problems.

**Comment by andreabalducci** [comment]
@jjrdk I wasn't on the team at that time, should ask Damian.

**Comment by alkampfergit** [comment]
@jjrdk Please check your pull request, because I've recently changed some files on the project to make it compliant with the GitVersion plugin for TeamCity. 

The change that broke your pull request is that, in src folder the file that was called VersionAssemblyInfo.cs should be renamed to AssemblyInfoCs.  The error in the build is

 CSC : error CS2001: Source file '..\VersionAssemblyInfo.cs' could not be found 

Moreover, since we are switching to Gitflow for all NeventStore projects, it is probably better for collaborators, to start doing modification from develop branch into a feature branch, then pull request against develop branch for the main repo (with @andreabalducci  we were speaking yesterday about creating a document to specify how to collaborate with gitflow).

**Comment by jjrdk** [comment]
I am going to close this PR since we have set up a [contrib project](https://github.com/jjrdk/NEventStore.Contrib) with Firebird support and published a [nuget package](https://www.nuget.org/packages/NEventStore.Contrib.Persistence/).

**Comment by andreabalducci** [comment]
@jjrdk do  you need a CI build? I'll take a look at the sources in the next weeks. thank you.

**Comment by jjrdk** [comment]
@andreabalducci - A CI build would be nice. I'll ping you as soon as we have the build scripting cleaned up.

**Comment by alkampfergit** [comment]
@andreabalducci  @jjrdk I've downloaded locally Firebird branch from jjrdk repository and rebased over actual Develop on a gitflow feature called feature/Firebird.

This could simplify the whole process. I had no conflicts on rebase, and I also fixed reference to the right assemblyinfo.cs files (that was renamed on develop branch).

Now we can use feature/Firebird feature branch, that can be synced on forked projects, and  pull request on main feature/Firebird until the feature is finished. once feature is finished we can close feature on Develop and move to the next release.

I've not still enabled firebird test on CI machine (we need to install and configure firebird first).

**Comment by jjrdk** [comment]
@alkampfergit @andreabalducci I am a little confused now. The first message was "create a contrib project", so I did. Now @alkampfergit is saying that there is a feature branch. Does this mean FirebirdSql support will be included in next release?

As for installing FirebirdSql, the it should not be necessary as the test setup uses the embedded database.

**Comment by andreabalducci** [comment]
@jjrdk it's a contrib project, imho should be NEventStore.Persistence.Firebird rather than NEventStore.Contrib.Firebird. 
With separated packages we can measure actual usage and decide what to include in the main project (supported by the team + community) and what to move to "contrib" projects (supported by community).

**Pull request closed without merging**
